version: 1
disable_existing_loggers: false
formatters:
  ist_formatter:
    "()": "guidelines_agent.core.custom_logging.ISTFormatter"
    format: "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
handlers:
  file:
    class: logging.FileHandler
    formatter: ist_formatter
    filename: logs/api_server.log
    mode: a
root:
  handlers: [file]
  level: INFO
loggers:
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [file]
    level: INFO
    propagate: false
